/*Filtering + Conditions
9.	Find all students learning from teacher ‘Meena’.
10.	Show only courses that have at least one student enrolled.
11.	Find teachers who don’t have any students assigned to them.
12.	List all students who are not in the ‘Python’ course.*/

SELECT S.NAME,T.TEACHER_NAME
FROM TEACHERS AS T INNER JOIN COURSES AS C
ON T.teacher_ID =C.TEACHER_ID
INNER JOIN 
STUDENTS AS S
ON C.COURSE_ID = S.COURSE_ID
WHERE TEACHER_NAME ='MEENA'

SELECT DISTINCT C.COURSE_NAME
FROM COURSES AS C INNER JOIN STUDENTS AS S
ON S.COURSE_ID =C.COURSE_ID

SELECT T.TEACHER_NAME
FROM TEACHERS AS T LEFT JOIN COURSES AS C
ON T.TEACHER_ID = C.TEACHER_ID
LEFT JOIN
 STUDENTS AS S
 ON C.COURSE_ID =S.COURSE_ID
 WHERE S.STUDENT_ID IS NULL

 SELECT S.NAME,C.COURSE_NAME
FROM STUDENTS AS S LEFT JOIN COURSES AS C
 ON C.COURSE_ID =S.COURSE_ID
 WHERE C.COURSE_NAME !='PYTHON'

 /* -SELF JOIN
    -CROSS JOIN
13. Find each employee’s manager name.
 14.Show all possible combinations of students and courses.*/

 SELECT E.EMP_NAME,M.EMP_NAME
 FROM EMPLOYEE AS E LEFT JOIN EMPLOYEE AS M
 ON E.MANAGER_ID =M.EMP_ID

 SELECT S.NAME,C.COURSE_NAME
 FROM STUDENTS AS S CROSS JOIN COURSES AS C

/*16.Find the total number of students per course (use GROUP BY + JOIN).
17.	List courses with no students enrolled.*/

 SELECT COURSE_NAME,COUNT(S.STUDENT_ID) AS TOTAL_STUDENTS
 FROM COURSES AS C LEFT JOIN STUDENTS AS S
 ON C.COURSE_ID =S.COURSE_ID
 GROUP BY
 C.COURSE_NAME;

SELECT C.COURSE_NAME
FROM COURSES AS C LEFT JOIN STUDENTS AS S
ON C.COURSE_ID = S.COURSE_id
WHERE 
S.STUDENT_ID IS NULL;

